module.exports = {
    USER: "user",
    PUBLIC: "public",
    STUDENT : "student",
    INSTRUCTOR: "instructor",
    ORGANIZATION: "organization",
    ORGANIZATION_ADMINISTRATOR: "organization-administrator",
    ORGANIZATION_DEPARTMENT_HEAD: "organization-department-head",
    ORGANIZATION_FINANCE_ADMIN: "organization-finance-admin",
    ORGANIZATION_HR_ADMIN: "organization-hr-admin",
    ORGANIZATION_HR_ASSISTANT: "organization-hr-assistant",
    ORGANIZATION_PAYROLL_MASTER: "organization-payroll-master",
    ORGANIZATION_STAFF: "organization-staff",
    ORGANIZATION_SUPERVISOR: "organization-supervisor",
    HOLDING_ADMINISTRATOR: "holding-administrator",
    ORGANIZATION_BRANCH_ADMINISTRATOR: "organization-branch-administrator",
    ORGANIZATION_WB_ADMINISTRATOR: "organization-wb-administrator",
    ORGANIZATION_TIME_ADMINISTRATOR: "organization-time-administrator",
    ORGANIZATION_FINANCIAL_ADMINISTRATOR: "organization-financial-administrator",
    ORGANIZATION_DIRECTORY_ADMINISTRATOR: "organization-directory-administrator",
    ORGANIZATION_COMPANY_ADMINISTRATOR: "organization-company-administrator",
    ORGANIZATION_ORGANIZATION_ADMINISTRATOR: "organization-organization-administrator",
    ORGANIZATION_LEARNING_ADMINISTRATOR: "organization-learning-administrator",
    ORGANIZATION_PERFORMANCE_ADMINISTRATOR: "organization-performance-administrator",
    ORGANIZATION_TALENT_ADMINISTRATOR: "organization-talent-administrator",
    ORGANIZATION_VENDOR_ADMINISTRATOR: "organization-vendor-administrator",
    ORGANIZATION_SURVEY_ADMINISTRATOR: "organization-survey-administrator",
    ORGANIZATION_DOCUMENT_ADMINISTRATOR: "organization-document-administrator",
    ORGANIZATION_SUPPORT_ADMINISTRATOR: "organization-support-administrator",
    ORGANIZATION_SETTINGS_ADMINISTRATOR: "organization-settings-administrator",
    ORGANIZATION_HOLDING_ADMINISTRATOR: "organization-holding-administrator",
    ORGANIZATION_BUDGET_ADMINISTRATOR: "organization-budget-administrator"
};